{
  "message": "ValueError: Exception encountered when calling layer \"reshape\" (type Reshape).\n\ntotal size of new array must be unchanged, input_shape = [18, 32], output_shape = [20, 32]\n\nCall arguments received by layer \"reshape\" (type Reshape):\n  â€¢ inputs=tf.Tensor(shape=(None, 18, 32), dtype=float32)\n\u001b[90mRun \u001b]8;;rstudio:run:reticulate::py_last_error()\u0007`reticulate::py_last_error()`\u001b]8;;\u0007 for details.\u001b[39m",
  "traceback": ["py_call_impl(callable, call_args$unnamed, call_args$named)", "layer(object, ...)", "compose_layer.default(object, x, ...)", "compose_layer(object, x, ...)", "layer_reshape(target_shape = c(lookback, 32))(conv_layer)", "eval(ei, envir)", "eval(ei, envir)", "withVisible(eval(ei, envir))", "tuning_run(\"LSTM_samples_script.R\", runs_dir = file.path(resultsdir, \n    \"1_units_filter\"), sample = 0.75, flags = list(batch_size = c(256), \n    conv_filters = c(12, 24), lstm_units = c(8, 32), dense_u = c(12, \n        24)))"]
}
